Tarea 2
Ximena González Lamadrid A01723927

In [2]:
import pandas as pd
import numpy as np

### Pregunta 1 

Almacena la información del archivo *cars.csv* en una variable llamada mis_datos y revisa su estructura.

In [3]:
mis_datos = pd.read_csv("cars.csv")

In [4]:
mis_datos.describe()
mis_datos.describe(include="all")

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
count,428,428,428,428,428,428.000000,428.000000,425.000000,425.000000,423.000000,426.000000,426.000000,423.000000,426.000000,427.000000
unique,38,425,6,3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Toyota,G35 4dr,Sedan,Asia,Front,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,28,2,262,158,226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,32774.855140,30014.700935,3.195294,5.811765,215.576832,20.065728,26.840376,3578.229314,108.166667,186.381733
std,NaN,NaN,NaN,NaN,NaN,19431.716674,17642.117750,1.111932,1.557802,71.978098,5.249574,5.749505,759.034549,8.327582,14.369110
min,NaN,NaN,NaN,NaN,NaN,10280.000000,9875.000000,1.300000,3.000000,73.000000,10.000000,12.000000,1850.000000,89.000000,143.000000
25%,NaN,NaN,NaN,NaN,NaN,20334.250000,18866.000000,2.300000,4.000000,165.000000,17.000000,24.000000,3103.000000,103.000000,178.000000
50%,NaN,NaN,NaN,NaN,NaN,27635.000000,25294.500000,3.000000,6.000000,210.000000,19.000000,26.000000,3476.000000,107.000000,187.000000
75%,NaN,NaN,NaN,NaN,NaN,39205.000000,35710.250000,3.900000,6.000000,252.500000,21.750000,29.000000,3978.500000,112.000000,194.000000
max,NaN,NaN,NaN,NaN,NaN,192465.000000,173560.000000,8.300000,12.000000,500.000000,60.000000,66.000000,7190.000000,144.000000,238.000000

### Pregunta 2 

Revisa si en la variable mis_datos existen missing values, de ser así reemplazalos por la media.

In [5]:
mis_datos.isna().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     3
Cylinders      3
Horsepower     5
MPG_City       2
MPG_Highway    2
Weight         5
Wheelbase      2
Length         1
dtype: int64

In [6]:
average_rate = mis_datos["EngineSize"].mean()
mis_datos["EngineSize"] = (
mis_datos["EngineSize"]
.fillna(average_rate)
)

average_rate = mis_datos["Cylinders"].mean()
mis_datos["Cylinders"] = (
mis_datos["Cylinders"]
.fillna(average_rate)
)

average_rate = mis_datos["Horsepower"].mean()
mis_datos["Horsepower"] = (
mis_datos["Horsepower"]
.fillna(average_rate)
)

average_rate = mis_datos["MPG_City"].mean()
mis_datos["MPG_City"] = (
mis_datos["MPG_City"]
.fillna(average_rate)
)

average_rate = mis_datos["MPG_Highway"].mean()
mis_datos["MPG_Highway"] = (
mis_datos["MPG_Highway"]
.fillna(average_rate)
)

average_rate = mis_datos["Weight"].mean()
mis_datos["Weight"] = (
mis_datos["Weight"]
.fillna(average_rate)
)

average_rate = mis_datos["Wheelbase"].mean()
mis_datos["Wheelbase"] = (
mis_datos["Wheelbase"]
.fillna(average_rate)
)

average_rate = mis_datos["Length"].mean()
mis_datos["Length"] = (
mis_datos["Length"]
.fillna(average_rate)
)

In [7]:
mis_datos.isna().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      0
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

### Pregunta 3 

Utilizando algoritmos con la variable mis_datos, responde las siguientes preguntas: 

¿Qué marca produce más vehículos y qué marca produce menos?

In [8]:
#make es marca
items = mis_datos['Make'].value_counts()
maxproductionid = items.idxmax()
maxproduction = items.max()

minproductionid = items.idxmin()
minproduction = items.min()

print(f"La marca con mayor producción de vehículos es {maxproductionid} con {maxproduction} vehículos.")
print(f"La marca con menor producción de vehículos es {minproductionid} con {minproduction} vehículos.")

La marca con mayor producción de vehículos es Toyota con 28 vehículos.
La marca con menor producción de vehículos es Hummer con 1 vehículos.

### Pregunta 4 

¿Cuántos autos se producen por región con transmisión delantera, cuántos con transmisión trasera y cuántos con doble transmisión (All)?

In [9]:
transmission = (
    mis_datos.groupby(["Origin", "DriveTrain"]).size()
)
print(transmission)

Origin  DriveTrain
Asia    All           34
        Front         99
        Rear          25
Europe  All           36
        Front         37
        Rear          50
USA     All           22
        Front         90
        Rear          35
dtype: int64

### Pregunta 5  

Encuentra cuál es el precio sugerido más caro, cuál es el precio sugerido más barato, las millas por galón promedio para ciudad y las millas por galón promedio para carretera

In [10]:
#checar que los datos que uso son numeros float o int
print(mis_datos.dtypes)

Make            object
Model           object
Type            object
Origin          object
DriveTrain      object
MSRP             int64
Invoice          int64
EngineSize     float64
Cylinders      float64
Horsepower     float64
MPG_City       float64
MPG_Highway    float64
Weight         float64
Wheelbase      float64
Length         float64
dtype: object

In [11]:
#minimos y maximos 

maxprice = mis_datos["MSRP"].max()
minprice = mis_datos["MSRP"].min()

print(f"El precio sugerido más caro es {maxprice}.")
print(f"El precio sugerido más barato es {minprice}.")

El precio sugerido más caro es 192465.
El precio sugerido más barato es 10280.

In [12]:
#promedios

cityavg = mis_datos["MPG_City"].mean()
highwayavg = mis_datos["MPG_Highway"].mean()

print(f"Las millas por galón promedio para ciudad son {cityavg:.2f}.")
print(f"Las millas por galón promedio para carretera son {highwayavg:.2f}.")

Las millas por galón promedio para ciudad son 20.07.
Las millas por galón promedio para carretera son 26.84.

### Pregunta 6 

Selecciona solo las variables Make, Model, Type, Origin, DriveTrain, MSRP, Weight, Wheelbase y Length. Conserva solo las observaciones cuyo DriveTrain sea Front y almacena esta información en una variable llamada mis_nuevos_datos.

In [13]:
selected_data = mis_datos[
[
"Make",
"Model",
"Type",
"Origin",
"DriveTrain",
"MSRP",
"Weight",
"Wheelbase",
"Length"
]
].copy()


mis_nuevos_datos = selected_data[
    selected_data["DriveTrain"] == "Front"
]

print(mis_nuevos_datos)

      Make                    Model   Type  Origin DriveTrain   MSRP  \
1    Acura           RSX Type S 2dr  Sedan    Asia      Front  23820
2    Acura                  TSX 4dr  Sedan    Asia      Front  26990
3    Acura                   TL 4dr  Sedan    Asia      Front  33195
4    Acura               3.5 RL 4dr  Sedan    Asia      Front  43755
5    Acura  3.5 RL w/Navigation 4dr  Sedan    Asia      Front  46100
..     ...                      ...    ...     ...        ...    ...
421  Volvo              S80 2.9 4dr  Sedan  Europe      Front  37730
423  Volvo  C70 LPT convertible 2dr  Sedan  Europe      Front  40565
424  Volvo  C70 HPT convertible 2dr  Sedan  Europe      Front  42565
425  Volvo               S80 T6 4dr  Sedan  Europe      Front  45210
426  Volvo                      V40  Wagon  Europe      Front  26135

          Weight  Wheelbase  Length
1    2778.000000      101.0   172.0
2    3230.000000      105.0   183.0
3    3578.229314      108.0   186.0
4    3880.000000      115.0   197.0
5    3893.000000      115.0   197.0
..           ...        ...     ...
421  3576.000000      110.0   190.0
423  3450.000000      105.0   186.0
424  3450.000000      105.0   186.0
425  3653.000000      110.0   190.0
426  2822.000000      101.0   180.0

[226 rows x 9 columns]

### Pregunta 7 

Imprime las primeras observaciones de la variable mis_nuevos_datos 

Con la información de la variable mis_nuevos_datos, necesitamos crear 3 nuevas variables, la primera llamada Weight_kilo que indique cuál es el peso del automóvil en kilos, la segunda llamada Wheelbase_cm que muestre el valor de la variable  Wheelbase en centímetros, y una última variable llamada Length_cm que indique la longitud del vehículo en centímetros. Almacena toda esta información dentro de la variable mis_nuevos_datos

In [14]:
mis_nuevos_datos.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Weight,Wheelbase,Length
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,2778.000000,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,3230.000000,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,33195,3578.229314,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,3880.000000,115.0,197.0
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,46100,3893.000000,115.0,197.0

In [15]:
# 1 libra es 0.453592 kg
mis_nuevos_datos["Weight_kilo"] = mis_nuevos_datos["Weight"] * 0.453592
mis_nuevos_datos.head()

/tmp/ipykernel_2335/2670649655.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mis_nuevos_datos["Weight_kilo"] = mis_nuevos_datos["Weight"] * 0.453592

,Make,Model,Type,Origin,DriveTrain,MSRP,Weight,Wheelbase,Length,Weight_kilo
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,2778.000000,101.0,172.0,1260.078576
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,3230.000000,105.0,183.0,1465.102160
3,Acura,TL 4dr,Sedan,Asia,Front,33195,3578.229314,108.0,186.0,1623.056191
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,3880.000000,115.0,197.0,1759.936960
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,46100,3893.000000,115.0,197.0,1765.833656

In [16]:
# 1 inch = 2.54 cm
mis_nuevos_datos["Wheelbase_cm"] = mis_nuevos_datos["Wheelbase"] * 0.453592
mis_nuevos_datos.head()

/tmp/ipykernel_2335/744039083.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mis_nuevos_datos["Wheelbase_cm"] = mis_nuevos_datos["Wheelbase"] * 0.453592

,Make,Model,Type,Origin,DriveTrain,MSRP,Weight,Wheelbase,Length,Weight_kilo,Wheelbase_cm
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,2778.000000,101.0,172.0,1260.078576,45.812792
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,3230.000000,105.0,183.0,1465.102160,47.627160
3,Acura,TL 4dr,Sedan,Asia,Front,33195,3578.229314,108.0,186.0,1623.056191,48.987936
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,3880.000000,115.0,197.0,1759.936960,52.163080
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,46100,3893.000000,115.0,197.0,1765.833656,52.163080

In [17]:
# 1 inch = 2.54 cm
mis_nuevos_datos["Length_cm"] = mis_nuevos_datos["Length"] * 0.453592
mis_nuevos_datos.head()

/tmp/ipykernel_2335/4065659162.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mis_nuevos_datos["Length_cm"] = mis_nuevos_datos["Length"] * 0.453592

,Make,Model,Type,Origin,DriveTrain,MSRP,Weight,Wheelbase,Length,Weight_kilo,Wheelbase_cm,Length_cm
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,2778.000000,101.0,172.0,1260.078576,45.812792,78.017824
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,3230.000000,105.0,183.0,1465.102160,47.627160,83.007336
3,Acura,TL 4dr,Sedan,Asia,Front,33195,3578.229314,108.0,186.0,1623.056191,48.987936,84.368112
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,3880.000000,115.0,197.0,1759.936960,52.163080,89.357624
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,46100,3893.000000,115.0,197.0,1765.833656,52.163080,89.357624

### Pregunta 8 

Con la información de la variable mis_nuevos_datos, crea una nueva variable llamada opinion que esté en función del precio sugerido para la venta. Si el precio es mayor a 60,000 el valor de la variable opinion debe ser "Expensive", si el precio está entre 60,000 y 30,000, la variable opinion debe decir "Normal". Y si el precio es menor a 30,000 la variable opinion debe sugerir "Inexpensive". Almacena la información en la variable mis_nuevos_datos

In [18]:
# price > 60000 = expensive
# price > 30000 y < 60000 = Normal
# price < 30000 = Inexpensive

def pricetag(MSRP):
    if MSRP > 60000:
        return "expensive"
    elif MSRP < 30000:
        return "Inexpensive"
    else:
        return "Normal"

mis_nuevos_datos["opinion"] = (mis_nuevos_datos["MSRP"].apply(pricetag))

mis_nuevos_datos.head()

/tmp/ipykernel_2335/2156600197.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mis_nuevos_datos["opinion"] = (mis_nuevos_datos["MSRP"].apply(pricetag))

,Make,Model,Type,Origin,DriveTrain,MSRP,Weight,Wheelbase,Length,Weight_kilo,Wheelbase_cm,Length_cm,opinion
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,2778.000000,101.0,172.0,1260.078576,45.812792,78.017824,Inexpensive
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,3230.000000,105.0,183.0,1465.102160,47.627160,83.007336,Inexpensive
3,Acura,TL 4dr,Sedan,Asia,Front,33195,3578.229314,108.0,186.0,1623.056191,48.987936,84.368112,Normal
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,3880.000000,115.0,197.0,1759.936960,52.163080,89.357624,Normal
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,46100,3893.000000,115.0,197.0,1765.833656,52.163080,89.357624,Normal

## Reflexión final

Aprender a manipular esta base de datos me ayudó a dejar mucho más en claro como es que por medio de programas como este se vuelve mucho más eficiente el extraer información relevante. A diferencia de excel, los calculos se hacen mucho más rápido y son escalables: es decir, puedo tener una base de datos del mismo tamaño, o cientos de veces más grande y el programa podrá devolver los análisis solicitados con la misma facilidad. Al pensar en usos dentro de las finanzas, me queda claro que la manipulacion de datos, como pueden ser registros de precios de acciones históricos de múltiples años se vuelve más conveniente en este tipo de programas antes que en Excel u otra aplicación. Además, es bastante amigable y fácil de operar con los ejemplos proporcionados en clase.